### PR TITLE
Omit PHP closing tags (PSR-2)

### PR DESCRIPTION
**Pull request by berry807**
Can cause unwanted output or PHP errors and following the [PSR-2 coding style guide](https://www.php-fig.org/psr/psr-2/#22-files).

### CODE REVIEW

**Comment by globalcitizen** [comment]
Thanks for the attempted contribution but this doesn't solve an actual problem.

**Comment by nicklog** [comment]
Just because a PR doesn't solve a problem doesn't mean it's pointless.
Like #71

**Comment by berry807** [comment]
I have to agree with @nicklog. And as quoted from CodeIgniter 

> The PHP closing tag on a PHP document ?> is optional to the PHP parser. However, if used, any whitespace following the closing tag, whether introduced by the developer, user, or an FTP application, can cause unwanted output, PHP errors, or if the latter are suppressed, blank pages. For this reason, all PHP files MUST OMIT the PHP closing tag and end with a single empty line instead.

**Comment by globalcitizen** [comment]
You will understand when you have experience maintaining systems longer
term. Brain time for users has value, and as maintainer I am their
benevolent gatekeeper. This one is an edge case, I see the theoretical
argument on recent versions... but change is not free. Right now I see no
possible way this could impact real world usage so it will not be merged.
Have a great weekend!

**Pull request closed without merging**
