### PR TITLE
Added IBAN registry for Congo

### PR DESCRIPTION
**Pull request by johnges**
Added IBAN registry for Congo by following the guidelines from the below URL

http://www.trustmerchantbank.com/modification-in-account-numbers/?lang=en

### CODE REVIEW

**Comment by globalcitizen** [comment]
Hi John, thanks for the contribution!

Unfortunately it seems to be inaccurate somewhere... let me explain.

Relevant output of `utils/test.php` ...

```
[CG (IANA:.cg, ISO3166-1 alpha-2:CG): Congo]
Is a SEPA member? No.
Central Bank: Central Bank of the Congo (http://www.bcc.cd/)
Has own team of bureaucrats? Yes.
Official currency: CDF
Example IBAN: CG39 3001 3020 0037 1072 1836 132
 - country  CG
 - checksum 39
 - bban     30013020003710721836132
 - bank     30013
 - branch   02000
 - account  3710721836132
 - natcksum

Checking validity... IBAN CG3930013020003710721836132 is valid.
```

This doesn't seem to gel with the [stated reference website](http://www.trustmerchantbank.com/modification-in-account-numbers/?lang=en).
* The reference website says that the account number should be 11 digits, however in the example you have provided (`3710721836132`) it is 13 digits.

Therefore, could you please get to the bottom of the issue and resolve it?

Also, normally it is preferable to collect and test against a range of IBAN from the country in question, to make sure everything is well defined. If you wouldn't mind, please include a file under `utils/example-ibans/cg-ibans` with a few of these gathered from around the web... this will assist with validating the new country.

Thanks!

**Comment by johnges** [comment]
Hi Walter,

The last two digit is RIB key. The function iban_get_account_part, does not consider the RIB keys at the end of BBAN and that is the reason, the account number becomes 13 digit. How do we proceed with this?

I have add two IBANs in the cg-ibans file

Thanks,
John

**Comment by globalcitizen** [comment]
Is the 'RIB key' a national checksum?

**Comment by johnges** [comment]
The reference website http://www.trustmerchantbank.com/modification-in-account-numbers/?lang=en
does not provide additional information on the 2 digit RIB key

**Comment by johnges** [comment]
Thank you very much

**Pull request merged**
